/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainPackage;

import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author marcelo
 */
public class Administracao extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    public Administracao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        btnVoltaTelaPrinci = new javax.swing.JButton();
        btnCadPacotes = new javax.swing.JButton();
        btnCadForn = new javax.swing.JButton();
        btnCadFunc = new javax.swing.JButton();
        btnCadProc = new javax.swing.JButton();
        btnCadSala = new javax.swing.JButton();
        btnDesabilitaconta = new javax.swing.JButton();
        btnEdtPacotes = new javax.swing.JButton();
        btnEdtProc = new javax.swing.JButton();
        btnEdtSala = new javax.swing.JButton();
        btnEdtFornecedor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CFRA - Cadastros");

        btnVoltaTelaPrinci.setIcon(new javax.swing.ImageIcon(getClass().getResource("/voltar.png"))); // NOI18N
        btnVoltaTelaPrinci.setText("Voltar");
        btnVoltaTelaPrinci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltaTelaPrinciActionPerformed(evt);
            }
        });

        btnCadPacotes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/package-icon.png"))); // NOI18N
        btnCadPacotes.setText("Cadastrar Pacotes");
        btnCadPacotes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCadPacotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadPacotesActionPerformed(evt);
            }
        });

        btnCadForn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fornecedor.png"))); // NOI18N
        btnCadForn.setText("Cadastrar Fornecedor");
        btnCadForn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCadForn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadFornActionPerformed(evt);
            }
        });

        btnCadFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user.png"))); // NOI18N
        btnCadFunc.setText("Cadastrar Usuário");
        btnCadFunc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCadFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadFuncActionPerformed(evt);
            }
        });

        btnCadProc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/procedimento.png"))); // NOI18N
        btnCadProc.setText("Cadastrar Procedimento");
        btnCadProc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCadProc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadProcActionPerformed(evt);
            }
        });

        btnCadSala.setIcon(new javax.swing.ImageIcon(getClass().getResource("/room.png"))); // NOI18N
        btnCadSala.setText("Cadastrar Sala");
        btnCadSala.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCadSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadSalaActionPerformed(evt);
            }
        });

        btnDesabilitaconta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/downaccount.png"))); // NOI18N
        btnDesabilitaconta.setText("Desabilitar Login");
        btnDesabilitaconta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDesabilitaconta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesabilitacontaActionPerformed(evt);
            }
        });

        btnEdtPacotes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/editpack.png"))); // NOI18N
        btnEdtPacotes.setText("Editar Pacotes");
        btnEdtPacotes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEdtPacotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdtPacotesActionPerformed(evt);
            }
        });

        btnEdtProc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        btnEdtProc.setText("Editar Procedimento");
        btnEdtProc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEdtProc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdtProcActionPerformed(evt);
            }
        });

        btnEdtSala.setIcon(new javax.swing.ImageIcon(getClass().getResource("/editSala.png"))); // NOI18N
        btnEdtSala.setText("Editar Salas");
        btnEdtSala.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEdtSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdtSalaActionPerformed(evt);
            }
        });

        btnEdtFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/editFornecedor.png"))); // NOI18N
        btnEdtFornecedor.setText("Editar Fornecedor");
        btnEdtFornecedor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEdtFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdtFornecedorActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(btnVoltaTelaPrinci, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnCadPacotes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnCadForn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnCadFunc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnCadProc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnCadSala, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnDesabilitaconta, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnEdtPacotes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnEdtProc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnEdtSala, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnEdtFornecedor, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnVoltaTelaPrinci)
                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jDesktopPane1Layout.createSequentialGroup()
                            .addComponent(btnCadProc)
                            .addGap(18, 18, 18)
                            .addComponent(btnEdtProc))
                        .addGroup(jDesktopPane1Layout.createSequentialGroup()
                            .addComponent(btnCadPacotes)
                            .addGap(18, 18, 18)
                            .addComponent(btnEdtPacotes))
                        .addGroup(jDesktopPane1Layout.createSequentialGroup()
                            .addComponent(btnCadSala)
                            .addGap(18, 18, 18)
                            .addComponent(btnEdtSala))
                        .addGroup(jDesktopPane1Layout.createSequentialGroup()
                            .addComponent(btnCadForn)
                            .addGap(18, 18, 18)
                            .addComponent(btnEdtFornecedor))
                        .addGroup(jDesktopPane1Layout.createSequentialGroup()
                            .addComponent(btnCadFunc)
                            .addGap(18, 18, 18)
                            .addComponent(btnDesabilitaconta))))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jDesktopPane1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCadForn, btnCadFunc, btnCadPacotes, btnCadProc, btnCadSala, btnDesabilitaconta, btnEdtFornecedor, btnEdtPacotes, btnEdtProc, btnEdtSala});

        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadFunc)
                    .addComponent(btnDesabilitaconta))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadProc)
                    .addComponent(btnEdtProc))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCadPacotes)
                    .addComponent(btnEdtPacotes))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadSala)
                    .addComponent(btnEdtSala))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCadForn)
                    .addComponent(btnEdtFornecedor))
                .addGap(18, 18, 18)
                .addComponent(btnVoltaTelaPrinci)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopPane1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCadForn, btnCadFunc, btnCadPacotes, btnCadProc, btnDesabilitaconta, btnEdtPacotes});

        jDesktopPane1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnEdtFornecedor, btnEdtSala});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadFuncActionPerformed
        CadastroProfissional cdf;
        try {
            cdf = new CadastroProfissional();
            cdf.setVisible(true);
            this.dispose();
        } catch (InterruptedException | ExecutionException ex) {
            Logger.getLogger(Administracao.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnCadFuncActionPerformed

    private void btnCadProcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadProcActionPerformed
        Procedimento cadproc = new Procedimento();
        cadproc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCadProcActionPerformed

    private void btnCadFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadFornActionPerformed
        Fornecedor cf;
        try {
            cf = new Fornecedor();
            cf.setVisible(true);
            this.dispose();
        } catch (InterruptedException | ExecutionException ex) {
            Logger.getLogger(Administracao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCadFornActionPerformed

    private void btnCadPacotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadPacotesActionPerformed
        Pacotes cadproc;
        try {
            cadproc = new Pacotes();
            cadproc.setVisible(true);
            this.dispose();
        } catch (InterruptedException | ExecutionException ex) {
            Logger.getLogger(Administracao.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnCadPacotesActionPerformed

    private void btnCadSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadSalaActionPerformed
        Salas cds = new Salas();
        cds.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCadSalaActionPerformed

    private void btnVoltaTelaPrinciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltaTelaPrinciActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVoltaTelaPrinciActionPerformed

    private void btnDesabilitacontaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesabilitacontaActionPerformed
        try {
            DesabilitaUser du = new DesabilitaUser();
            du.setVisible(true);
            this.dispose();
        } catch (InterruptedException | ExecutionException ex) {
            Logger.getLogger(Administracao.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnDesabilitacontaActionPerformed

    private void btnEdtPacotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdtPacotesActionPerformed
        PacotesFilter cadpac;
        try {
            cadpac = new PacotesFilter();
            cadpac.setVisible(true);
        } catch (InterruptedException | ExecutionException ex) {
            Logger.getLogger(Administracao.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnEdtPacotesActionPerformed

    private void btnEdtProcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdtProcActionPerformed
        ProcedimentoFilter procFilter;
        try {
            procFilter = new ProcedimentoFilter();
            procFilter.setVisible(true);
        } catch (InterruptedException | ExecutionException ex) {
            Logger.getLogger(Administracao.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnEdtProcActionPerformed

    private void btnEdtSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdtSalaActionPerformed
        SalasFilter sf;
        try {
            sf = new SalasFilter();
            sf.setVisible(true);
        } catch (InterruptedException | ExecutionException ex) {
            Logger.getLogger(Administracao.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnEdtSalaActionPerformed

    private void btnEdtFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdtFornecedorActionPerformed
        FornecedorFilter frf;
        try {
            frf = new FornecedorFilter();
            frf.setVisible(true);
        } catch (InterruptedException | ExecutionException ex) {
            Logger.getLogger(Administracao.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnEdtFornecedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Administracao().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadForn;
    private javax.swing.JButton btnCadFunc;
    private javax.swing.JButton btnCadPacotes;
    private javax.swing.JButton btnCadProc;
    private javax.swing.JButton btnCadSala;
    private javax.swing.JButton btnDesabilitaconta;
    private javax.swing.JButton btnEdtFornecedor;
    private javax.swing.JButton btnEdtPacotes;
    private javax.swing.JButton btnEdtProc;
    private javax.swing.JButton btnEdtSala;
    private javax.swing.JButton btnVoltaTelaPrinci;
    private javax.swing.JDesktopPane jDesktopPane1;
    // End of variables declaration//GEN-END:variables
}
