/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainPackage;

import com.google.api.core.ApiFuture;
import com.google.cloud.firestore.DocumentReference;
import com.google.cloud.firestore.WriteResult;
import java.awt.Component;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author marcelo
 */
public class Salas extends javax.swing.JFrame {

    /**
     * Creates new form CadastroSalas
     */
    public Salas() {
        initComponents();
        btnAtualizarSala.setVisible(false);
    }

    Salas(ModelSala sala) {
        initComponents();
        initSalaField(sala);
        btnNovaSala.setVisible(false);
        this.setTitle("CFRA - Editar Sala");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        edtNomeSala = new javax.swing.JTextField();
        btnNovaSala = new javax.swing.JButton();
        txtIdSala = new javax.swing.JLabel();
        btnAtualizarSala = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        comboQtdPacientes = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CFRA - Cadasrto Salas");

        jLabel1.setText("Nome da Sala:");

        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/voltar.png"))); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnNovaSala.setIcon(new javax.swing.ImageIcon(getClass().getResource("/confirmar.png"))); // NOI18N
        btnNovaSala.setText("Confirmar");
        btnNovaSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaSalaActionPerformed(evt);
            }
        });

        btnAtualizarSala.setIcon(new javax.swing.ImageIcon(getClass().getResource("/confirmar.png"))); // NOI18N
        btnAtualizarSala.setText("Atualizar");
        btnAtualizarSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarSalaActionPerformed(evt);
            }
        });

        jLabel2.setText("Limite de pacientes por horário:");

        comboQtdPacientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Qtd. Máx. de Pacientes", "1", "2", "3", "4", "5", "6", "7", "8" }));

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnVoltar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(edtNomeSala, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnNovaSala, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtIdSala, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnAtualizarSala, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(comboQtdPacientes, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(edtNomeSala))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAtualizarSala)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNovaSala))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdSala)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboQtdPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(edtNomeSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboQtdPacientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdSala)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovaSala)
                    .addComponent(btnVoltar)
                    .addComponent(btnAtualizarSala))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovaSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaSalaActionPerformed
        if ("".equals(edtNomeSala.getText())) {
            Component frame = null;
            JOptionPane.showMessageDialog(frame,
                    "Nome da sala vazio. Favor inserir um nome!");
        } else if ("Qtd. Máx. de Pacientes".equals(comboQtdPacientes.getSelectedItem().toString())) {
            Component frame = null;
            JOptionPane.showMessageDialog(frame,
                    "Favor escolher o número máximo de pacientes simultâneos para essa sala!");
        } else {
            //Firebase insert
            FireBaseClient fbDb = new FireBaseClient();
            String uuid = java.util.UUID.randomUUID().toString();
            DocumentReference docRef = fbDb.FirebaseInt().collection("salas").document(uuid);
            ModelSala ms = new ModelSala();

            ms.setidSala(uuid);
            ms.setNomeSala(edtNomeSala.getText());
            ms.setQtdPaciente(Integer.parseInt(comboQtdPacientes.getSelectedItem().toString()));

            ApiFuture<WriteResult> result = docRef.set(ms);
            try {
                System.out.println("Update time : " + result.get().getUpdateTime());
                Component frame = null;
                JOptionPane.showMessageDialog(frame,
                        "Sala cadastrada com sucesso!");
                edtNomeSala.setText("");

            } catch (InterruptedException | ExecutionException ex) {
                Logger.getLogger(Anamnese.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_btnNovaSalaActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnAtualizarSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarSalaActionPerformed
        if ("".equals(edtNomeSala.getText())) {
            Component frame = null;
            JOptionPane.showMessageDialog(frame,
                    "O nome da sala não pode ser vazio!");
        } else if ("Qtd. Máx. de Pacientes".equals(comboQtdPacientes.getSelectedItem().toString())) {
            Component frame = null;
            JOptionPane.showMessageDialog(frame,
                    "Favor escolher o número máximo de pacientes simultâneos para essa sala!");
        } else {
            ModelSala ms = new ModelSala();

            ms.setidSala(txtIdSala.getText());
            ms.setNomeSala(edtNomeSala.getText());
            ms.setQtdPaciente(Integer.parseInt(comboQtdPacientes.getSelectedItem().toString()));

            FireBaseClient fbc = new FireBaseClient();
            DocumentReference docRef = fbc.FirebaseInt().collection("salas").document(txtIdSala.getText());
            ApiFuture<WriteResult> result = docRef.set(ms);
            try {
                System.out.println("Update time : " + result.get().getUpdateTime());
                Component frame = null;
                JOptionPane.showMessageDialog(frame,
                        "Sala atualizada com sucesso!");
                edtNomeSala.setText("");

            } catch (InterruptedException | ExecutionException ex) {
                Logger.getLogger(Anamnese.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.dispose();
        }

    }//GEN-LAST:event_btnAtualizarSalaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Salas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Salas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Salas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Salas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Salas().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizarSala;
    private javax.swing.JButton btnNovaSala;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> comboQtdPacientes;
    private javax.swing.JTextField edtNomeSala;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel txtIdSala;
    // End of variables declaration//GEN-END:variables

    private void initSalaField(ModelSala sala) {

        txtIdSala.setText(sala.getidSala());
        txtIdSala.setVisible(false);
        edtNomeSala.setText(sala.getNomeSala());
        comboQtdPacientes.setSelectedItem(Integer.toString(sala.getQtdPaciente()));
    }
}
