/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainPackage;

import com.google.api.core.ApiFuture;
import com.google.cloud.firestore.DocumentReference;
import com.google.cloud.firestore.WriteResult;
import java.awt.Component;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URL;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author marcelo
 */
public class TelaPrincipal extends javax.swing.JFrame {

    boolean visibilidade;

    /**
     * Creates new form TelaPrincipal
     *
     * @throws java.lang.InterruptedException
     * @throws java.util.concurrent.ExecutionException
     * @throws java.io.IOException
     */
    public TelaPrincipal() throws InterruptedException, ExecutionException, IOException {
        initComponents();
        visibilidade = false;
        setvisible(visibilidade);
        visibilidade = true;
        initLogo();
    }

    TelaPrincipal(String perfil) throws InterruptedException, ExecutionException {

        System.out.println("Perfil 2--> " + perfil);
        initComponents();
        visibilidade = false;
        setvisible(visibilidade);
        visibilidade = true;
        initLogo();

        panelFunc.setVisible(false);
        panelAdmin.setVisible(false);

        if (null != perfil) {
            switch (perfil) {
                case "Admin":
                    panelFunc.setVisible(false);
                    panelAdmin.setVisible(true);
                    break;
                case "Func":
                    panelAdmin.setVisible(false);
                    panelFunc.setVisible(true);
                    break;
                case "AdminFunc":
                    panelFunc.setVisible(true);
                    panelAdmin.setVisible(true);
                    break;
                default:
                    break;
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopCadastro = new javax.swing.JDesktopPane();
        txtEndereco = new javax.swing.JLabel();
        txtNome = new javax.swing.JLabel();
        txtDataAvaliacao = new javax.swing.JLabel();
        txtSexo = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JLabel();
        txtIdade = new javax.swing.JLabel();
        txtEstadoCivil = new javax.swing.JLabel();
        edtNome = new javax.swing.JTextField();
        edtEndereco = new javax.swing.JTextField();
        edtTelefone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JLabel();
        edtEmail = new javax.swing.JTextField();
        txtCpf = new javax.swing.JLabel();
        edtCpf = new javax.swing.JTextField();
        edtSexo = new javax.swing.JComboBox<>();
        edtEstadoCivil = new javax.swing.JComboBox<>();
        edtDataAval = new com.toedter.calendar.JDateChooser();
        txtwhatsup = new javax.swing.JLabel();
        edtWhatsapp = new javax.swing.JComboBox<>();
        edtIdade = new com.toedter.calendar.JDateChooser();
        panelFunc = new javax.swing.JPanel();
        btnAgendamentos = new javax.swing.JButton();
        btnAgendaWeb = new javax.swing.JButton();
        btnEvolucaoDiaria = new javax.swing.JButton();
        btnConsultarPaciente = new javax.swing.JButton();
        btnCadastroCliente = new javax.swing.JButton();
        btnAgenda = new javax.swing.JButton();
        panelAdmin = new javax.swing.JPanel();
        btnCadastro = new javax.swing.JButton();
        btnRelatorioEntr = new javax.swing.JButton();
        btnSaidas = new javax.swing.JButton();
        btnRelatorioSaidas = new javax.swing.JButton();
        btnPacotes = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnAnaminese = new javax.swing.JButton();
        btnDadosCad = new javax.swing.JButton();
        btnImportarPacientes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CFRA - Fisio App");

        jDesktopCadastro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jDesktopCadastro.setPreferredSize(new java.awt.Dimension(650, 350));

        txtEndereco.setText("Endereço:");

        txtNome.setText("Nome:");

        txtDataAvaliacao.setText("Data Avaliação:");

        txtSexo.setText("Sexo:");

        txtTelefone.setText("Telefone:");

        txtIdade.setText("Dt. Nascimento:");

        txtEstadoCivil.setText("Estado Civil:");

        txtEmail.setText("Email:");

        txtCpf.setText("CPF:");

        edtSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Indiferente", "Feminino", "Masculino" }));

        edtEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Indiferente", "Solteiro(a)", "Casado(a)", "Separado(a)", "Divorciado(a)", "Viúvo(a)" }));

        txtwhatsup.setText("Whatsapp:");

        edtWhatsapp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));

        panelFunc.setBackground(new java.awt.Color(12, 177, 75));

        btnAgendamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/scheduleList.png"))); // NOI18N
        btnAgendamentos.setText("Agendamentos");
        btnAgendamentos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAgendamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendamentosActionPerformed(evt);
            }
        });

        btnAgendaWeb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schedule.png"))); // NOI18N
        btnAgendaWeb.setText("Agenda Web");
        btnAgendaWeb.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAgendaWeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendaWebActionPerformed(evt);
            }
        });

        btnEvolucaoDiaria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diary-book-icon2.png"))); // NOI18N
        btnEvolucaoDiaria.setText("Evolução Diária");
        btnEvolucaoDiaria.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEvolucaoDiaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEvolucaoDiariaActionPerformed(evt);
            }
        });

        btnConsultarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/procurar.png"))); // NOI18N
        btnConsultarPaciente.setText("Consultar Paciente");
        btnConsultarPaciente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnConsultarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarPacienteActionPerformed(evt);
            }
        });

        btnCadastroCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paciente.png"))); // NOI18N
        btnCadastroCliente.setText("Novo Paciente");
        btnCadastroCliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroClienteActionPerformed(evt);
            }
        });

        btnAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schedule2.png"))); // NOI18N
        btnAgenda.setText("Agendar/Remarcar");
        btnAgenda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFuncLayout = new javax.swing.GroupLayout(panelFunc);
        panelFunc.setLayout(panelFuncLayout);
        panelFuncLayout.setHorizontalGroup(
            panelFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFuncLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCadastroCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConsultarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFuncLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgendamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgendaWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEvolucaoDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelFuncLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAgenda, btnAgendaWeb, btnAgendamentos, btnCadastroCliente, btnConsultarPaciente, btnEvolucaoDiaria});

        panelFuncLayout.setVerticalGroup(
            panelFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFuncLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCadastroCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsultarPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgendamentos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addComponent(btnAgendaWeb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEvolucaoDiaria)
                .addContainerGap())
        );

        panelFuncLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAgenda, btnAgendaWeb, btnAgendamentos, btnCadastroCliente, btnConsultarPaciente, btnEvolucaoDiaria});

        panelAdmin.setBackground(new java.awt.Color(12, 177, 75));

        btnCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadastro.png"))); // NOI18N
        btnCadastro.setText("Administração");
        btnCadastro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroActionPerformed(evt);
            }
        });

        btnRelatorioEntr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sales-report-icon.png"))); // NOI18N
        btnRelatorioEntr.setText("Relatório Entradas");
        btnRelatorioEntr.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRelatorioEntr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioEntrActionPerformed(evt);
            }
        });

        btnSaidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/money.png"))); // NOI18N
        btnSaidas.setText("Fluxo de Caixa");
        btnSaidas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSaidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaidasActionPerformed(evt);
            }
        });

        btnRelatorioSaidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sales-report-icon2.png"))); // NOI18N
        btnRelatorioSaidas.setText("Relatório Saídas");
        btnRelatorioSaidas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRelatorioSaidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioSaidasActionPerformed(evt);
            }
        });

        btnPacotes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/associarpkt.png"))); // NOI18N
        btnPacotes.setText("Associar Pacotes");
        btnPacotes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPacotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPacotesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAdminLayout = new javax.swing.GroupLayout(panelAdmin);
        panelAdmin.setLayout(panelAdminLayout);
        panelAdminLayout.setHorizontalGroup(
            panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnRelatorioSaidas, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRelatorioEntr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSaidas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCadastro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnPacotes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelAdminLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCadastro, btnRelatorioEntr, btnRelatorioSaidas, btnSaidas});

        panelAdminLayout.setVerticalGroup(
            panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSaidas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRelatorioEntr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRelatorioSaidas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPacotes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelAdminLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCadastro, btnRelatorioEntr, btnRelatorioSaidas, btnSaidas});

        jPanel3.setBackground(new java.awt.Color(12, 177, 75));

        btnAnaminese.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medical.png"))); // NOI18N
        btnAnaminese.setText("Anamnese");
        btnAnaminese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnamineseActionPerformed(evt);
            }
        });

        btnDadosCad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        btnDadosCad.setText("Salvar");
        btnDadosCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDadosCadActionPerformed(evt);
            }
        });

        btnImportarPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/importar.png"))); // NOI18N
        btnImportarPacientes.setText("Importar Pacientes");
        btnImportarPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarPacientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDadosCad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAnaminese)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImportarPacientes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDadosCad)
                    .addComponent(btnAnaminese)
                    .addComponent(btnImportarPacientes))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopCadastro.setLayer(txtEndereco, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopCadastro.setLayer(txtNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopCadastro.setLayer(txtDataAvaliacao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopCadastro.setLayer(txtSexo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopCadastro.setLayer(txtTelefone, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopCadastro.setLayer(txtIdade, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopCadastro.setLayer(txtEstadoCivil, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopCadastro.setLayer(edtNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopCadastro.setLayer(edtEndereco, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopCadastro.setLayer(edtTelefone, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopCadastro.setLayer(txtEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopCadastro.setLayer(edtEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopCadastro.setLayer(txtCpf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopCadastro.setLayer(edtCpf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopCadastro.setLayer(edtSexo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopCadastro.setLayer(edtEstadoCivil, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopCadastro.setLayer(edtDataAval, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopCadastro.setLayer(txtwhatsup, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopCadastro.setLayer(edtWhatsapp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopCadastro.setLayer(edtIdade, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopCadastro.setLayer(panelFunc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopCadastro.setLayer(panelAdmin, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopCadastro.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopCadastroLayout = new javax.swing.GroupLayout(jDesktopCadastro);
        jDesktopCadastro.setLayout(jDesktopCadastroLayout);
        jDesktopCadastroLayout.setHorizontalGroup(
            jDesktopCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopCadastroLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jDesktopCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopCadastroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jDesktopCadastroLayout.createSequentialGroup()
                        .addGroup(jDesktopCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopCadastroLayout.createSequentialGroup()
                                .addGroup(jDesktopCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIdade)
                                    .addComponent(txtTelefone)
                                    .addComponent(txtDataAvaliacao)
                                    .addComponent(txtEmail)
                                    .addComponent(txtCpf)
                                    .addComponent(txtEstadoCivil)
                                    .addComponent(txtSexo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jDesktopCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(edtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jDesktopCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(edtIdade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(edtEstadoCivil, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(edtSexo, javax.swing.GroupLayout.Alignment.LEADING, 0, 171, Short.MAX_VALUE))
                                    .addGroup(jDesktopCadastroLayout.createSequentialGroup()
                                        .addGroup(jDesktopCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(edtCpf, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(edtEmail, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(edtTelefone)
                                            .addComponent(edtDataAval, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtwhatsup)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(edtWhatsapp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jDesktopCadastroLayout.createSequentialGroup()
                                .addComponent(txtNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtEndereco))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)))
                .addGroup(jDesktopCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jDesktopCadastroLayout.setVerticalGroup(
            jDesktopCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopCadastroLayout.createSequentialGroup()
                .addGroup(jDesktopCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jDesktopCadastroLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jDesktopCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNome)
                            .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdade, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(edtIdade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEstadoCivil, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(edtEstadoCivil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDesktopCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSexo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(edtSexo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDesktopCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtEndereco)
                            .addComponent(edtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDataAvaliacao, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(edtDataAval, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(edtTelefone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtwhatsup, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(edtWhatsapp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edtEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCpf)
                            .addComponent(edtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopCadastroLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(panelFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jDesktopCadastroLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {edtCpf, edtDataAval, edtEmail, edtEndereco, edtEstadoCivil, edtIdade, edtNome, edtSexo, edtTelefone, edtWhatsapp});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopCadastro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 821, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed
        Administracao cdstr = new Administracao();
        cdstr.setVisible(true);
    }//GEN-LAST:event_btnCadastroActionPerformed

    private void btnAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendaActionPerformed

        try {
            AgendaMenu ag = null;
            ag = new AgendaMenu();
            ag.setVisible(true);
        } catch (InterruptedException | ExecutionException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnAgendaActionPerformed

    private void btnSaidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaidasActionPerformed
        Saidas saida;
        try {
            saida = new Saidas();
            saida.setVisible(true);
        } catch (InterruptedException | ExecutionException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnSaidasActionPerformed

    private void btnAgendamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendamentosActionPerformed
        ListaCalendarioFilter clf;
        try {
            clf = new ListaCalendarioFilter();
            clf.setVisible(true);
        } catch (InterruptedException | ExecutionException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnAgendamentosActionPerformed

    private void btnRelatorioSaidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioSaidasActionPerformed
        RelatorioSaidas rlt = new RelatorioSaidas();
        rlt.setVisible(true);
    }//GEN-LAST:event_btnRelatorioSaidasActionPerformed

    private void btnConsultarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarPacienteActionPerformed
        ConsultarPaciente cpc;
        try {
            cpc = new ConsultarPaciente();
            cpc.setVisible(true);
            //this.dispose();
        } catch (InterruptedException | ExecutionException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnConsultarPacienteActionPerformed

    private void btnEvolucaoDiariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEvolucaoDiariaActionPerformed
        try {
            EvolucaoDiariaMenu evd = new EvolucaoDiariaMenu();
            evd.setVisible(true);
        } catch (InterruptedException | ExecutionException ex) {
            Logger.getLogger(TelaPrincipalEditarPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEvolucaoDiariaActionPerformed

    private void btnPacotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPacotesActionPerformed
        AssociaPacotes asspac;
        try {
            asspac = new AssociaPacotes();
            asspac.setVisible(true);
        } catch (InterruptedException | ExecutionException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnPacotesActionPerformed

    private void btnDadosCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDadosCadActionPerformed
        ModelPaciente pc = new ModelPaciente();

        if ("".equals(edtNome.getText()) || edtDataAval.getDate() == null) {
            Component frame = null;
            JOptionPane.showMessageDialog(frame,
                    "Favor preencher todos os campos!");

        } else {
            pc.setnome(edtNome.getText());
            final DateFormat df = new SimpleDateFormat("dd-MM-yyyy");
            String idade = df.format(edtIdade.getDate());
            pc.setidade(idade);
            pc.setsexo(edtSexo.getSelectedItem().toString());
            pc.setestadoCivil(edtEstadoCivil.getSelectedItem().toString());
            pc.setendereco(edtEndereco.getText());
            pc.setdataAvaliacao(df.format(edtDataAval.getDate()));

            String phone = edtTelefone.getText().replace("-", "").replace("/", "").trim();
            pc.settelefone(phone.replaceAll("\\s+", ""));
            pc.setcpf(edtCpf.getText());
            pc.setEmail(edtEmail.getText());
            pc.setWhatsapp(edtWhatsapp.getSelectedItem().toString());
            pc.setConvenio("não se aplica");
            pc.setConvenioNum("não se aplica");

            pc.setqueixaPrin("Informação não cadastrada");
            pc.sethistDoePrin("Informação não cadastrada");
            pc.setapLocomotor("Informação não cadastrada");
            pc.setapCardioResp("Informação não cadastrada");
            pc.setapVascular("Informação não cadastrada");
            pc.setapGinec("Informação não cadastrada");
            pc.setapOutros("Informação não cadastrada");
            pc.sethistFamiliar("Informação não cadastrada");
            pc.setsinaisVitais("Informação não cadastrada");
            pc.setdiagCli("Informação não cadastrada");

            //id para o documenti
            String uuid = java.util.UUID.randomUUID().toString();
            pc.setId(uuid);

            FireBaseClient fbc = new FireBaseClient();

            DocumentReference docRef = fbc.FirebaseInt().collection("pacientes").document(uuid);
            ApiFuture<WriteResult> result = docRef.set(pc);
            try {
                System.out.println("Update time : " + result.get().getUpdateTime());
                Component frame = null;
                JOptionPane.showMessageDialog(frame,
                        "Paciente cadastrado com sucesso!");

            } catch (InterruptedException | ExecutionException ex) {
                Logger.getLogger(Anamnese.class.getName()).log(Level.SEVERE, null, ex);
            }

            edtNome.setText("");
            //edtIdade.setText("");
            edtSexo.setSelectedIndex(0);
            edtEstadoCivil.setSelectedIndex(0);
            edtEndereco.setText("");
            edtTelefone.setText("");
            edtCpf.setText("");
            edtEmail.setText("");

        }
    }//GEN-LAST:event_btnDadosCadActionPerformed

    private void btnAnamineseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnamineseActionPerformed
        ModelPaciente pc = new ModelPaciente();

        if ("".equals(edtNome.getText()) || edtDataAval.getDate() == null) {
            Component frame = null;
            JOptionPane.showMessageDialog(frame,
                    "Favor preencher todos os campos!");

        } else {
            pc.setnome(edtNome.getText());
            final DateFormat df = new SimpleDateFormat("dd-MM-yyyy");
            pc.setidade(df.format(edtIdade.getDate()));
            pc.setsexo(edtSexo.getSelectedItem().toString());
            pc.setestadoCivil(edtEstadoCivil.getSelectedItem().toString());
            pc.setendereco(edtEndereco.getText());

            pc.setdataAvaliacao(df.format(edtDataAval.getDate()));

            String phone = edtTelefone.getText().replace("-", "").replace("/", "").trim();
            pc.settelefone(phone.replaceAll("\\s+", ""));
            pc.setcpf(edtCpf.getText());
            pc.setEmail(edtEmail.getText());
            pc.setWhatsapp(edtWhatsapp.getSelectedItem().toString());

            //id para o documenti
            String uuid = java.util.UUID.randomUUID().toString();
            pc.setId(uuid);

            edtNome.setText("");
            //edtIdade.setText("");
            edtSexo.setSelectedIndex(0);
            edtEstadoCivil.setSelectedIndex(0);

            edtEndereco.setText("");
            edtTelefone.setText("");
            edtCpf.setText("");
            edtEmail.setText("");
            Anamnese anm = new Anamnese(pc);
            anm.setVisible(true);
        }
    }//GEN-LAST:event_btnAnamineseActionPerformed

    private void btnRelatorioEntrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioEntrActionPerformed
        RelatorioEntradas reltEntr;
        try {
            reltEntr = new RelatorioEntradas();
            reltEntr.setVisible(true);
        } catch (InterruptedException | ExecutionException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnRelatorioEntrActionPerformed

    private void btnAgendaWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendaWebActionPerformed
        String url = "https://calendar.google.com/";
        openWebpage(url);
    }//GEN-LAST:event_btnAgendaWebActionPerformed

    private void btnCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroClienteActionPerformed
        if (visibilidade == true) {
            setvisible(visibilidade);
            visibilidade = false;
        } else {
            setvisible(visibilidade);
            visibilidade = true;
            initLogo();
        }
    }//GEN-LAST:event_btnCadastroClienteActionPerformed

    private void btnImportarPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarPacientesActionPerformed
        ImportarPacientes ip = new ImportarPacientes();
        ip.setVisible(true);
    }//GEN-LAST:event_btnImportarPacientesActionPerformed

    public static void openWebpage(String urlString) {
        try {
            Desktop.getDesktop().browse(new URL(urlString).toURI());
        } catch (IOException | URISyntaxException e) {
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new TelaPrincipal().setVisible(true);
                } catch (InterruptedException | ExecutionException | IOException ex) {
                    Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgenda;
    private javax.swing.JButton btnAgendaWeb;
    private javax.swing.JButton btnAgendamentos;
    private javax.swing.JButton btnAnaminese;
    private javax.swing.JButton btnCadastro;
    private javax.swing.JButton btnCadastroCliente;
    private javax.swing.JButton btnConsultarPaciente;
    private javax.swing.JButton btnDadosCad;
    private javax.swing.JButton btnEvolucaoDiaria;
    private javax.swing.JButton btnImportarPacientes;
    private javax.swing.JButton btnPacotes;
    private javax.swing.JButton btnRelatorioEntr;
    private javax.swing.JButton btnRelatorioSaidas;
    private javax.swing.JButton btnSaidas;
    private javax.swing.JTextField edtCpf;
    private com.toedter.calendar.JDateChooser edtDataAval;
    private javax.swing.JTextField edtEmail;
    public javax.swing.JTextField edtEndereco;
    private javax.swing.JComboBox<String> edtEstadoCivil;
    private com.toedter.calendar.JDateChooser edtIdade;
    public static javax.swing.JTextField edtNome;
    private javax.swing.JComboBox<String> edtSexo;
    public javax.swing.JTextField edtTelefone;
    private javax.swing.JComboBox<String> edtWhatsapp;
    private javax.swing.JDesktopPane jDesktopCadastro;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel panelAdmin;
    private javax.swing.JPanel panelFunc;
    private javax.swing.JLabel txtCpf;
    private javax.swing.JLabel txtDataAvaliacao;
    private javax.swing.JLabel txtEmail;
    private javax.swing.JLabel txtEndereco;
    private javax.swing.JLabel txtEstadoCivil;
    private javax.swing.JLabel txtIdade;
    private javax.swing.JLabel txtNome;
    private javax.swing.JLabel txtSexo;
    private javax.swing.JLabel txtTelefone;
    private javax.swing.JLabel txtwhatsup;
    // End of variables declaration//GEN-END:variables

    private void setvisible(boolean b) {
        txtNome.setVisible(b);
        txtNome.setText("Nome");
        txtNome.setIcon(null);
        edtNome.setVisible(b);
        txtIdade.setVisible(b);
        edtIdade.setVisible(b);
        txtSexo.setVisible(b);
        edtSexo.setVisible(b);
        txtEstadoCivil.setVisible(b);
        edtEstadoCivil.setVisible(b);
        txtEndereco.setVisible(b);
        edtEndereco.setVisible(b);
        txtDataAvaliacao.setVisible(b);
        edtDataAval.setVisible(b);
        txtTelefone.setVisible(b);
        edtTelefone.setVisible(b);
        txtwhatsup.setVisible(b);
        edtWhatsapp.setVisible(b);
        txtEmail.setVisible(b);
        edtEmail.setVisible(b);
        txtCpf.setVisible(b);
        edtCpf.setVisible(b);
        btnDadosCad.setVisible(b);
        btnAnaminese.setVisible(b);
        jPanel3.setVisible(b);

    }

    private void initLogo() {
        txtNome.setVisible(true);
        ImageIcon iconLogo = new ImageIcon(getClass().getClassLoader().getResource("logo.png"));
        txtNome.setText("");
        txtNome.setIcon(iconLogo);
    }

}
